apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 15
  selector:
    matchLabels:
      app: weather-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - image: cicdcontainer01.azurecr.io/cicdcontainerrepo:latest
        imagePullPolicy: IfNotPresent
        name: weather-api
        # env:
        #   - name: CURRENCY_EXCHANGE_SERVICE_HOST
        #     value: http://currency-exchange
        
        #     valueFrom: 
        #       configMapKeyRef:
        #         key: CURRENCY_EXCHANGE_SERVICE_HOST
        #         name: currency-conversion-config-map
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: weather-api
  name: weather-api
  namespace: default
spec:
  ports:
  - port: 80 #CHANGE
    protocol: TCP
    targetPort: 80 #CHANGE
  selector:
    app: weather-api
  sessionAffinity: None #CHANGE
  type: LoadBalancer